# -*- coding: utf-8 -*-
"""NLP HW3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1lAVgRhZG2Q2lfdSQ9TETK1WnXLrt_HK_
"""

import nltk
nltk.download('content')

# read the sentences from the file sentences.txt
sentfile = open('/content/Exemplar Sentences beta.txt', 'r')
# make a list of sentences, separating the tokens by white space.
sentence_list = []
for line in sentfile:
    sentence_list.append(line.split())

# read the grammar file - the nltk data function load will not reload
#    the file unless you set the cache to be False
camg = nltk.data.load('/content/camelot_grammar2.cfg', cache=False)

# create a recursive descent parser
cam_parser = nltk.RecursiveDescentParser(camg)

# for each sentence print it and its parse trees
# if the grammar cannot parse a sentence, sometimes it gives an error and
#    sometimes it just goes on to the next sentence with no parse tree
for sent in sentence_list:
    print(sent)
    for tree in cam_parser.parse(sent):
        print (tree)